FROM node:8.11.4-alpine

WORKDIR /home/app/

COPY .babelrc package*.json webpack*.js /home/app/
COPY src /home/app/src

RUN npm install

#ENV TERAVOZ_URL https://api.teravoz.com.br/
#ENV TERAVOZ_USER "silvioluiz"
#ENV TERAVOZ_PASSWORD "L3nAVS>E/:,7AnW:"
#ENV PORT 3000

RUN ["npm","run", "build"]
CMD ["npm","run", "start-webhook"]