version: '3'

services:
  webhook:
    #image: webhook-stable
    ports: 
      - "3000:3000"
    expose:
      - "3000"
    networks: 
      main:
        aliases:
          - webhook
    build: 
      context: .
      dockerfile: Dockerfile-webhook
  teravoz:
    ports:
      - "3001:3001"
    expose:
      - "3001"
    networks:
      main:
        aliases:
          - teravoz
    build:
      context: .
      dockerfile: Dockerfile-teravoz
networks: 
  main: