FROM node:8.11.4-alpine

WORKDIR /home/app/

COPY .babelrc package*.json webpack*.js /home/app/
COPY src /home/app/src

RUN npm install

ENV WEBHOOK_HOST "http://webhook"
ENV WEBHOOK_PORT 3000

RUN ["npm","run", "build"]
CMD ["npm","run", "start-teravoz"]