version: '3'

services:
  webhook:
    #image: webhook-stable
    ports: 
      - "3000:3000"
    links: teravoz
    build: 
      context: .
      dockerfile: Dockerfile-webhook
    depends_on: 
      - teravoz
  teravoz:
    ports:
      - "3001:3001"
    links: 
      - webhook
    build:
      context: .
      dockerfile: Dockerfile-teravoz